### ISSUE TITLE
GPLink: Get-DscConfiguration / Test-DscConfiguration throws an exception if the target OU doesn't exist

### ISSUE THREAD

**Issue by oliveirt** [citadelgroup/GroupPolicyDsc#6]
Where a GPLink and dependent Organizational Unit are defined in the same configuration, it is not possible to successfully run Get-DscConfiguration against the configuration (prior to the apply). Instead an exception is thrown, where ideally should just indicate that the required GPLink is not present.

Sample configuration is provided below to reproduce the error. 

````
Configuration testConfiguration {
    [CmdletBinding(SupportsShouldProcess=$false, PositionalBinding=$false)]
    param(
    )

    if (!$PSBoundParameters.ContainsKey('OutputPath')) {
        Throw "A OutputPath parameter is mandatory." 
    }

    if ($null -eq $Domain)
    { 
        $Domain = Get-ADDomain
    }

    Import-DscResource -ModuleName PSDesiredStateConfiguration
    Import-DscResource -ModuleName ActivedirectoryDsc
    Import-DscResource -ModuleName GroupPolicyDsc

    ADOrganizationalUnit DoesNotYetExist
    {
        Name = "DoesNotYetExist"
        Path = $Domain.distinguishedName
        Ensure = 'Present'
    }

    GroupPolicy GpoA
    {
        Name = "TestGpo"
        Ensure = 'Present'
        Status = 'AllSettingsEnabled'
    }

    GpLink GpoALink
    {
        GPOName = "GpoA"
        Path = ("OU=DoesNotYetExist," + $Domain.distinguishedName)
        Enabled = 'Yes'
        Ensure = 'Present'
        DependsOn = @('[ADOrganizationalUnit]DoesNotYetExist', '[GroupPolicy]GpoA ')
    }
}
````

Running Test-DscConfiguration prior to the apply should generate
VERBOSE: [DC1]: LCM:  [ Start  Test     ]  [[GPLink]GpoALink]
There is no such object on the server. (Exception from HRESULT: 0x80072030)
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.GroupPolicy.Commands.GetGPInheritanceCommand
    + PSComputerName        : localhost

**Comment by dancs85** [comment]
Merged
